version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Diamond12@
    ports:
      - "1435:1433"
    networks:
      - spring-boot-network

  app:
    image: diamondstore
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge
